# Generated by Django 4.2.16 on 2026-09-17 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('OTP_SENT', 'OTP Sent'), ('PHONE_VERIFIED', 'Phone Verified'), ('APP_SUBMITTED', 'Application Submitted'), ('APP_UNDER_REVIEW', 'Application Under Review'), ('APP_APPROVED', 'Application Approved'), ('APP_REJECTED', 'Application Rejected'), ('NEW_APPLICATION', 'New Application Submitted')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notif_user_read_idx'), models.Index(fields=['user', 'created_at'], name='notif_user_time_idx')],
            },
        ),
    ]
